### ISSUE TITLE
添加可信域名 返回的内容与校验文件内容不一致

### ISSUE THREAD

**Issue by zzlKevin** [Chanjet/chanjet-openapi-java-demo#1]
添加可信域名 一直报错 返回的内容与校验文件内容不一致
CHANJET_CHECK.txt已经在根目录，而且浏览器访问域名/CHANJET_CHECK.txt，也能访问到正确的文件内容，但是添加域名就是不行，换了很多账号租户都一样，是不是出问题了

**Comment by zhangliang198722** [comment]
请提校验的域名

**Comment by zzlKevin** [comment]
ctvmkffu.beesnat.com

**Comment by zzlKevin** [comment]
老师，可否提供邮箱交流

**Comment by zzlKevin** [comment]
这个是我本地映射的，晚些可能会断开
ctvmkffu.beesnat.com
这个是长期存在的。也是一样的
ghcbs.hfcapp.com

**Comment by zhangliang198722** [comment]
需要您确认 您绑定域名的开发者账号企业id是否为 123xxxxxx660
没个开发者账号的校验文件是不同的
您这个校验文件仅能将安全域名绑定在企业id为123xxxxxx660 开发者企业下。
如果问题仍未解决，可以微信中搜索  畅捷通开放平台 ，菜单中选择 开放对接 -> 客服咨询

**Comment by zzlKevin** [comment]
是3805结尾，可是不是只要可信域名管理里下载的"CHANJET_CHECK.txt" 的内容和域名根目录的文件内容一致就可以了吗

**Comment by zzlKevin** [comment]
这个校验文件就是3805结尾的企业里面下载的呀，怎么是660结尾？
可否告知解码算法@zhangliang198722

**Comment by zzlKevin** [comment]
是3805结尾，可是不是只要可信域名管理里下载的"CHANJET_CHECK.txt" 的内容和域名根目录的文件内容一致就可以了吗
这个校验文件就是3805结尾的企业里面下载的呀，怎么是660结尾？
可否告知解码算法

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月31日(周五) 中午11:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Chanjet/chanjet-openapi-java-demo] 添加可信域名 返回的内容与校验文件内容不一致 (Issue #1)




 
需要您确认 您绑定域名的开发者账号企业id是否为 123660
 没个开发者账号的校验文件是不同的
 您这个校验文件仅能将安全域名绑定在企业id为123660 开发者企业下。
 如果问题仍未解决，可以微信中搜索  畅捷通开放平台 ，菜单中选择 开放对接 -&gt; 客服咨询

**Comment by zzlKevin** [comment]
客服没人值守，没回复

**Comment by zhangliang198722** [comment]
> 客服没人值守，没回复


> 客服没人值守，没回复

问题留言，后续会有人联系您
